config/routes.rb
Rails.application.routes.draw do
  # get 'sessions/new'
  # get 'sessions/create'

  get '/sign_out', to: 'sessions#destroy', as: :sign_out
  resources :sessions, only: [:new, :create]

  get "up" => "rails/health#show", as: :rails_health_check

  get '/courses', to: redirect('/')
  resources :courses

  root "courses#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :courses

  validates :name, uniqueness: true

  def self.options_for_select
    pluck(:name, :id)
  end
end

app/controllers/api/courses_controller.rb
class Api::CoursesController < ApplicationController
  def index
    @courses = Course.all

    render json: @courses
  end

  def show
    @course = Course.find(params[:id])

    render json: @course
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def authenticate!
    unless session[:user_id].blank?
      @current_user = User.find(session[:user_id])
    else
      flash[:alert] = "You need to sign in"
      redirect_to sign_in_path
    end
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[ show edit update destroy ]

  # GET /courses
  def index
    @courses = Course.all
  end

  # GET /courses/1
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
    # current_user = User.find(session[:user_id])

    # if @course.user != current_user
    #   flash[:alert] = "No Permission"

    #   redirect_to course_path(@course)
    #   return
    # end
  end

  # POST /courses
  def create
    @course = Course.new(course_params)

    if @course.save
      redirect_to @course, notice: "Course was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /courses/1
  def update
    # current_user = User.find(session[:user_id])

    # if @course.user != current_user
    #   flash[:alert] = "No Permission"

    #   redirect_to course_path(@course)
    #   return
    # end

    if @course.update(course_params)
      redirect_to @course, notice: "Course was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /courses/1
  def destroy
    @course.destroy!
    redirect_to courses_url, notice: "Course was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:name, :body, :summary, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    name = params[:name]
    password = params[:password]

    user = User.find_by(name: name)

    if (!user.nil? && user.authenticate(password))
      flash[:notice] = "Sign In Success as: #{user.name}"
      session[:user_id] = user.id
      session[:user_name] = user.name

      redirect_to root_path
    else
      flash[:alert] = "Wrong"

      redirect_to new_session_path
    end
  end

  def destroy
    session[:user_id] = nil
    session[:user_name] = nil

    flash[:notice] = "Sign Out Success"

    redirect_to root_path
  end
end

app/helpers/api/courses_helper.rb
module Api::CoursesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/courses/_course.html.erb
<div id="<%= dom_id course %>">
  <p>
    <%= link_to course.name, course %>
  </p>

  <% if course.user %>
    <p>
      user: <%= course.user&.name %>
    </p>
  <% end %>

  <p>
    <strong>Description:</strong>
    <%= course.body %>
  </p>

  <p>
    <strong>Summary:</strong>
    <%= course.summary %>
  </p>

</div>

app/views/courses/_form.html.erb
<%= form_with(model: course) do |form| %>
  <% if course.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
        <% course.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.label :summary, style: "display: block" %>
    <%= form.text_field :summary %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.select :user_id, User.options_for_select %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render "form", course: @course %>

<br>

<div>
  <%= link_to "Show this course", @course %> |
  <%= link_to "Back to courses", courses_path %>
</div>

app/views/courses/index.html.erb
<p style="color: green"><%= notice %></p>


<% if session[:user_name] %>
<p>
  Signed in as: <%= session[:user_name] %>
</p>

<%= link_to 'Sign Out', sign_out_path, data: { turbo: false } %>

<% else %>

<a href="<%= new_session_path%>">Sign In</a>
<% end %>

<h1>Courses</h1>

<div id="courses">
  <% @courses.each do |course| %>
    <%= render course %>
  <% end %>
</div>

<%= link_to "New course", new_course_path %>

app/views/courses/new.html.erb
<h1>New course</h1>

<%= render "form", course: @course %>

<br>

<div>
  <%= link_to "Back to courses", courses_path %>
</div>

app/views/courses/show.html.erb
<p style="color: green"><%= notice %></p>
<p style="color: red"><%= alert %></p>

<%= render @course %>

<div>
  <%= link_to "Edit this course", edit_course_path(@course) %> |
  <%= link_to "Back to courses", courses_path %>

  <%= button_to "Destroy this course", @course, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trainings</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>